version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '9090:9090'
    restart: unless-stopped
    environment:
      PORT: '9090'
      DATABASE_DSN: root:pa55_worD@tcp(localhost:3306)/xm?charset=utf8mb4&parseTime=True&loc=Local
    networks:
      - backend

  db:
    image: mysql:8.0.29
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=xm
      - MYSQL_ROOT_PASSWORD=pa55_worD
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:

volumes:
  mysql-data: